version: 2.0

jobs:
    build:
        docker:
            - image: armageddonknight/texlive:latest
        steps:
            - checkout
            - run: 
                name: Build PDF Artifact
                command: |
                    mkdir -p /tmp/artifacts/
                    make all
                    cp main.pdf /tmp/artifacts/
            - run: 
                name: Decode Access Token
                command: |
                    openssl aes-256-cbc -d -in include/.gitoken_encrypted -k $GITHUB_KEY > .gitoken
            - run:
                name: Download HUB Toolkit
                command: |
                    wget https://github.com/github/hub/releases/download/v2.5.0/hub-linux-amd64-2.5.0.tgz
                    tar zxvf hub-linux-amd64-2.5.0.tgz
            - run:
                name: Update Latest Release
                command: |
                    source .gitoken && PATH=$PATH:hub-linux-amd64-2.5.0/bin
                    hub release delete latest
                    hub release create -a main.pdf -m "Latest PDF Artifact" latest
            - store_artifacts:
                path: /tmp/artifacts
