version: 2.0

jobs:
    build:
        docker:
            - image: armageddonknight/latex_include:latest
        steps:
            - checkout
            - run: 
                name: Build PDF Artifact
                command: |
                    mkdir -p /tmp/artifacts/
                    make all
                    cp main.pdf /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts
