name: build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Prerequisite
              run: |
                sudo apt-get update
                sudo apt-get install -y texlive-full make
            - name: Build
              run: make
